# Site settings
title: Aakash Shetty
tagline: On a journey called Life!
author: Aakash Shetty
# twitter:
#   username: 
#   card: summary
logo: /assets/images/icon.webp
social:
  name: Aakash Shetty
  links:
    # - https://twitter.com/
    # - https://www.facebook.com/
    - https://www.linkedin.com/in/aakash-shetty-928a29183/
    - https://github.com/AAKASHKSHETTY/

lang: en-US
resume_link: /assets/Resume/Resume(vim).pdf
baseurl: ""
url: "https://AAKASHKSHETTY.github.io/"
firstname: Aakash
secondname: Shetty
general_email: aks9108@nyu.edu

# Build settings
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  parse_block_html: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: false
sass:
  style: compressed

# Other options
permalink: /:title/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

algolia:
  application_id: OWPETZ9UYV
  index_name: site_search
  search_only_api_key: a2056bd20cce65e7c4a939b867d91040S
